export * from './crm/_services';
export * from './crm/campaigns';
export * from './crm/leads';
export * from './crm/opportunities';
export * from './crm/followups';
export * from './sales/orders';
export * from './sales/goals';
export * from './sales/customer';
export * from './stock/movements';
export * from './stock/products';
export * from './stock/productsProps';
export * from './stock/suppliers';
export * from './financial/invoiceEntries';
export * from './financial/invoiceExit';
export * from './financial/invoiceEntries';
export * from './humanResources/employees';
export * from './sales/purchaseRequest';
export * from './financial/company';

